---
# file: sshauth.yml

- hosts: all:!empanada.bl.fcen.uba.ar
  gather_facts: true
  become: true
  become_user: root
  roles:
    - users
  vars_files:
    - vars/secrets.yml
  environment:
    http_proxy: http://proxy.fcen.uba.ar:8080
